version: '3'
services:
  ftp:
    build: ./
    ports: 
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=anton|${PASS}
      - ADDRESS=172.16.16.203
    volumes:
      - ./ftp:/ftp/anton
